#############################################################################
# Makefile for building: OSCGraph.app/Contents/MacOS/OSCGraph
# Generated by qmake (3.1) (Qt 5.9.1)
# Project:  OSCGraph/OSCGraph.pro
# Template: app
# Command: /Users/connerlacy/Qt/5.9.1/clang_64/bin/qmake -o Makefile OSCGraph/OSCGraph.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -IOSCGraph -I. -I/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCharts.framework/Headers -I/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/macx-clang -F/Users/connerlacy/Qt/5.9.1/clang_64/lib
QMAKE         = /Users/connerlacy/Qt/5.9.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/connerlacy/Qt/5.9.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/connerlacy/Qt/5.9.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = OSCGraph1.0.0
DISTDIR = /Users/connerlacy/Documents/CoHack/GroupFlow/Repositories/groupflow_software/.tmp/OSCGraph1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/connerlacy/Qt/5.9.1/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/connerlacy/Qt/5.9.1/clang_64/lib -framework QtCharts -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = OSCGraph/main.cpp \
		OSCGraph/mainwindow.cpp \
		OSCGraph/osc/OscPrintReceivedElements.cpp \
		OSCGraph/osc/OscOutboundPacketStream.cpp \
		OSCGraph/osc/OscTypes.cpp \
		OSCGraph/ip/posix/NetworkingUtils.cpp \
		OSCGraph/ip/posix/UdpSocket.cpp \
		OSCGraph/ip/IpEndpointName.cpp \
		OSCGraph/osc/OscReceivedElements.cpp \
		OSCGraph/oscreceiver.cpp \
		OSCGraph/graph.cpp moc_mainwindow.cpp \
		moc_oscreceiver.cpp \
		moc_graph.cpp
OBJECTS       = main.o \
		mainwindow.o \
		OscPrintReceivedElements.o \
		OscOutboundPacketStream.o \
		OscTypes.o \
		NetworkingUtils.o \
		UdpSocket.o \
		IpEndpointName.o \
		OscReceivedElements.o \
		oscreceiver.o \
		graph.o \
		moc_mainwindow.o \
		moc_oscreceiver.o \
		moc_graph.o
DIST          = /Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/spec_pre.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/qdevice.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/device_config.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/unix.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/mac.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/macx.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/sanitize.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/gcc-base.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/clang.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/clang-mac.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/qconfig.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/qt_functions.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/qt_config.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/spec_post.prf \
		../../../.qmake.stash \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/toolchain.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/default_pre.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/resolve_config.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/default_post.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/qml_debug.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/warn_on.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/qt.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/resources.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/moc.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/uic.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/unix/thread.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/qmake_use.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/file_copies.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/rez.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/exceptions.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/yacc.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/lex.prf \
		OSCGraph/OSCGraph/OSCGraph.pro OSCGraph/mainwindow.h \
		OSCGraph/ip/IpEndpointName.h \
		OSCGraph/ip/NetworkingUtils.h \
		OSCGraph/ip/PacketListener.h \
		OSCGraph/ip/TimerListener.h \
		OSCGraph/ip/UdpSocket.h \
		OSCGraph/osc/MessageMappingOscPacketListener.h \
		OSCGraph/osc/OscException.h \
		OSCGraph/osc/OscHostEndianness.h \
		OSCGraph/osc/OscOutboundPacketStream.h \
		OSCGraph/osc/OscPacketListener.h \
		OSCGraph/osc/OscPrintReceivedElements.h \
		OSCGraph/osc/OscReceivedElements.h \
		OSCGraph/osc/OscTypes.h \
		OSCGraph/oscreceiver.h \
		OSCGraph/graph.h OSCGraph/main.cpp \
		OSCGraph/mainwindow.cpp \
		OSCGraph/osc/OscPrintReceivedElements.cpp \
		OSCGraph/osc/OscOutboundPacketStream.cpp \
		OSCGraph/osc/OscTypes.cpp \
		OSCGraph/ip/posix/NetworkingUtils.cpp \
		OSCGraph/ip/posix/UdpSocket.cpp \
		OSCGraph/ip/IpEndpointName.cpp \
		OSCGraph/osc/OscReceivedElements.cpp \
		OSCGraph/oscreceiver.cpp \
		OSCGraph/graph.cpp
QMAKE_TARGET  = OSCGraph
DESTDIR       = 
TARGET        = OSCGraph.app/Contents/MacOS/OSCGraph

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d OSCGraph.app/Contents/MacOS/ || mkdir -p OSCGraph.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OSCGraph/OSCGraph.pro /Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/macx-clang/qmake.conf /Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/spec_pre.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/qdevice.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/device_config.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/unix.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/mac.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/macx.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/sanitize.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/gcc-base.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/clang.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/clang-mac.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/qconfig.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/qt_functions.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/qt_config.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/spec_post.prf \
		../../../../.qmake.stash \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/toolchain.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/default_pre.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/resolve_config.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/default_post.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/qml_debug.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/warn_on.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/qt.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/resources.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/moc.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/uic.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/unix/thread.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/qmake_use.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/file_copies.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/rez.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/exceptions.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/yacc.prf \
		/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/lex.prf \
		OSCGraph/OSCGraph.pro \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCharts.framework/QtCharts.prl \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile OSCGraph/OSCGraph.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/spec_pre.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/qdevice.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/device_config.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/unix.conf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/mac.conf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/macx.conf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/sanitize.conf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/gcc-base.conf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/clang.conf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/common/clang-mac.conf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/qconfig.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/qt_functions.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/qt_config.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/spec_post.prf:
../../../../.qmake.stash:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/sdk.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/toolchain.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/default_pre.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/resolve_config.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/default_post.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/default_post.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/qml_debug.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/warn_on.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/qt.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/resources.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/moc.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/unix/opengl.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/uic.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/unix/thread.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/qmake_use.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/file_copies.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/rez.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/testcase_targets.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/exceptions.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/yacc.prf:
/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/lex.prf:
OSCGraph/OSCGraph.pro:
/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCharts.framework/QtCharts.prl:
/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile OSCGraph/OSCGraph.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

OSCGraph.app/Contents/PkgInfo: 
	@test -d OSCGraph.app/Contents || mkdir -p OSCGraph.app/Contents
	@$(DEL_FILE) OSCGraph.app/Contents/PkgInfo
	@echo "APPL????" > OSCGraph.app/Contents/PkgInfo
OSCGraph.app/Contents/Resources/empty.lproj: 
	@test -d OSCGraph.app/Contents/Resources || mkdir -p OSCGraph.app/Contents/Resources
	@touch OSCGraph.app/Contents/Resources/empty.lproj
	
OSCGraph.app/Contents/Info.plist: 
	@test -d OSCGraph.app/Contents || mkdir -p OSCGraph.app/Contents
	@$(DEL_FILE) OSCGraph.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,bebopsensors.OSCGraph,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,OSCGraph,g" -e "s,@LIBRARY@,OSCGraph,g" -e "s,@TYPEINFO@,????,g" /Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/macx-clang/Info.plist.app >OSCGraph.app/Contents/Info.plist

all: Makefile \
		OSCGraph.app/Contents/PkgInfo \
		OSCGraph.app/Contents/Resources/empty.lproj \
		OSCGraph.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents OSCGraph/mainwindow.h OSCGraph/ip/IpEndpointName.h OSCGraph/ip/NetworkingUtils.h OSCGraph/ip/PacketListener.h OSCGraph/ip/TimerListener.h OSCGraph/ip/UdpSocket.h OSCGraph/osc/MessageMappingOscPacketListener.h OSCGraph/osc/OscException.h OSCGraph/osc/OscHostEndianness.h OSCGraph/osc/OscOutboundPacketStream.h OSCGraph/osc/OscPacketListener.h OSCGraph/osc/OscPrintReceivedElements.h OSCGraph/osc/OscReceivedElements.h OSCGraph/osc/OscTypes.h OSCGraph/oscreceiver.h OSCGraph/graph.h $(DISTDIR)/
	$(COPY_FILE) --parents OSCGraph/main.cpp OSCGraph/mainwindow.cpp OSCGraph/osc/OscPrintReceivedElements.cpp OSCGraph/osc/OscOutboundPacketStream.cpp OSCGraph/osc/OscTypes.cpp OSCGraph/ip/posix/NetworkingUtils.cpp OSCGraph/ip/posix/UdpSocket.cpp OSCGraph/ip/IpEndpointName.cpp OSCGraph/osc/OscReceivedElements.cpp OSCGraph/oscreceiver.cpp OSCGraph/graph.cpp $(DISTDIR)/
	$(COPY_FILE) --parents OSCGraph/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r OSCGraph.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h /Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_oscreceiver.cpp moc_graph.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_oscreceiver.cpp moc_graph.cpp
moc_mainwindow.cpp: /Users/connerlacy/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		OSCGraph/oscreceiver.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		OSCGraph/osc/OscReceivedElements.h \
		OSCGraph/osc/OscTypes.h \
		OSCGraph/osc/OscException.h \
		OSCGraph/osc/OscPacketListener.h \
		OSCGraph/ip/PacketListener.h \
		OSCGraph/ip/UdpSocket.h \
		OSCGraph/ip/NetworkingUtils.h \
		OSCGraph/ip/IpEndpointName.h \
		OSCGraph/graph.h \
		OSCGraph/mainwindow.h \
		moc_predefs.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/bin/moc
	/Users/connerlacy/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/macx-clang -I/Users/connerlacy/Documents/CoHack/GroupFlow/Repositories/groupflow_software/OSCGraph -I/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCharts.framework/Headers -I/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -F/Users/connerlacy/Qt/5.9.1/clang_64/lib OSCGraph/mainwindow.h -o moc_mainwindow.cpp

moc_oscreceiver.cpp: /Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		OSCGraph/osc/OscReceivedElements.h \
		OSCGraph/osc/OscTypes.h \
		OSCGraph/osc/OscException.h \
		OSCGraph/osc/OscPacketListener.h \
		OSCGraph/ip/PacketListener.h \
		OSCGraph/ip/UdpSocket.h \
		OSCGraph/ip/NetworkingUtils.h \
		OSCGraph/ip/IpEndpointName.h \
		OSCGraph/oscreceiver.h \
		moc_predefs.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/bin/moc
	/Users/connerlacy/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/macx-clang -I/Users/connerlacy/Documents/CoHack/GroupFlow/Repositories/groupflow_software/OSCGraph -I/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCharts.framework/Headers -I/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -F/Users/connerlacy/Qt/5.9.1/clang_64/lib OSCGraph/oscreceiver.h -o moc_oscreceiver.cpp

moc_graph.cpp: OSCGraph/graph.h \
		moc_predefs.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/bin/moc
	/Users/connerlacy/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/connerlacy/Qt/5.9.1/clang_64/mkspecs/macx-clang -I/Users/connerlacy/Documents/CoHack/GroupFlow/Repositories/groupflow_software/OSCGraph -I/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCharts.framework/Headers -I/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -F/Users/connerlacy/Qt/5.9.1/clang_64/lib OSCGraph/graph.h -o moc_graph.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: OSCGraph/mainwindow.ui \
		/Users/connerlacy/Qt/5.9.1/clang_64/bin/uic
	/Users/connerlacy/Qt/5.9.1/clang_64/bin/uic OSCGraph/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: OSCGraph/main.cpp OSCGraph/mainwindow.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		OSCGraph/oscreceiver.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		OSCGraph/osc/OscReceivedElements.h \
		OSCGraph/osc/OscTypes.h \
		OSCGraph/osc/OscException.h \
		OSCGraph/osc/OscPacketListener.h \
		OSCGraph/ip/PacketListener.h \
		OSCGraph/ip/UdpSocket.h \
		OSCGraph/ip/NetworkingUtils.h \
		OSCGraph/ip/IpEndpointName.h \
		OSCGraph/graph.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o OSCGraph/main.cpp

mainwindow.o: OSCGraph/mainwindow.cpp OSCGraph/mainwindow.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		OSCGraph/oscreceiver.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		OSCGraph/osc/OscReceivedElements.h \
		OSCGraph/osc/OscTypes.h \
		OSCGraph/osc/OscException.h \
		OSCGraph/osc/OscPacketListener.h \
		OSCGraph/ip/PacketListener.h \
		OSCGraph/ip/UdpSocket.h \
		OSCGraph/ip/NetworkingUtils.h \
		OSCGraph/ip/IpEndpointName.h \
		OSCGraph/graph.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o OSCGraph/mainwindow.cpp

OscPrintReceivedElements.o: OSCGraph/osc/OscPrintReceivedElements.cpp OSCGraph/osc/OscPrintReceivedElements.h \
		OSCGraph/osc/OscReceivedElements.h \
		OSCGraph/osc/OscTypes.h \
		OSCGraph/osc/OscException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OscPrintReceivedElements.o OSCGraph/osc/OscPrintReceivedElements.cpp

OscOutboundPacketStream.o: OSCGraph/osc/OscOutboundPacketStream.cpp OSCGraph/osc/OscOutboundPacketStream.h \
		OSCGraph/osc/OscTypes.h \
		OSCGraph/osc/OscException.h \
		OSCGraph/osc/OscHostEndianness.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OscOutboundPacketStream.o OSCGraph/osc/OscOutboundPacketStream.cpp

OscTypes.o: OSCGraph/osc/OscTypes.cpp OSCGraph/osc/OscTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OscTypes.o OSCGraph/osc/OscTypes.cpp

NetworkingUtils.o: OSCGraph/ip/posix/NetworkingUtils.cpp OSCGraph/ip/NetworkingUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NetworkingUtils.o OSCGraph/ip/posix/NetworkingUtils.cpp

UdpSocket.o: OSCGraph/ip/posix/UdpSocket.cpp OSCGraph/ip/UdpSocket.h \
		OSCGraph/ip/NetworkingUtils.h \
		OSCGraph/ip/IpEndpointName.h \
		OSCGraph/ip/PacketListener.h \
		OSCGraph/ip/TimerListener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UdpSocket.o OSCGraph/ip/posix/UdpSocket.cpp

IpEndpointName.o: OSCGraph/ip/IpEndpointName.cpp OSCGraph/ip/IpEndpointName.h \
		OSCGraph/ip/NetworkingUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IpEndpointName.o OSCGraph/ip/IpEndpointName.cpp

OscReceivedElements.o: OSCGraph/osc/OscReceivedElements.cpp OSCGraph/osc/OscReceivedElements.h \
		OSCGraph/osc/OscTypes.h \
		OSCGraph/osc/OscException.h \
		OSCGraph/osc/OscHostEndianness.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OscReceivedElements.o OSCGraph/osc/OscReceivedElements.cpp

oscreceiver.o: OSCGraph/oscreceiver.cpp OSCGraph/oscreceiver.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Users/connerlacy/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		OSCGraph/osc/OscReceivedElements.h \
		OSCGraph/osc/OscTypes.h \
		OSCGraph/osc/OscException.h \
		OSCGraph/osc/OscPacketListener.h \
		OSCGraph/ip/PacketListener.h \
		OSCGraph/ip/UdpSocket.h \
		OSCGraph/ip/NetworkingUtils.h \
		OSCGraph/ip/IpEndpointName.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oscreceiver.o OSCGraph/oscreceiver.cpp

graph.o: OSCGraph/graph.cpp OSCGraph/graph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graph.o OSCGraph/graph.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_oscreceiver.o: moc_oscreceiver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_oscreceiver.o moc_oscreceiver.cpp

moc_graph.o: moc_graph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graph.o moc_graph.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

